os: osx
osx_image: xcode11.1
language: swift
env:
  global:
    - secure: "ceWI2swzBzRILNZShuxTkRYis9E4r3q4TDseAOWHC5Matt4XLpbDMk4PV20s3TCjP3hC/eHVjtiXlP8GrY5dN3pjjEHLV1mw28fXb8OVP7sA1c3RjIY3ETgGfP/uGMi4ZcfCFO+RBsEAPPiUFiNQ9C1HqE5vXwuU08HIKPziDuOWOw6gCTXJwEr3fJu73o5Fwk089M45l8+uS1c+wgIhgbjbvHlAwlZjrxpS4PcuHPvh5M0y5TJ1mDDJCPr/Do8Ns/flV8eLGK+vLR9VRKgbCoianoH5vhclXkYnLXlIgBfKUz0j/KYLmLa0FYRIekSTZTye8TG1+XuMisy5IjSRZZPpFL9bXcbUdWzmw30kOWzHQF8Yfn96nqhgq4V+xWNY6ww/UvyC4tnNNGW9C4VdqjAmZIPN9DkKmfJpyR8GdGtBwonDDzxsQxlkyrzvCtCu6HnYmIFieJ7QjJSTyZwlhNWDJh7WBQDq6O80VIBAp1GofBg9uInn0CaNifmGYYMhQGCe5wT8HyaR0Sdnuf5C/Hm1NTmG3rfVNHZAhd9CjD6+4Q2U/+mT+1XKrB1QKXNQinwctOVqK7dUbY3zBMxj8/DiCBPnS7WUj1n5Mu0mBK8c3MdNTzzyGjvi5ciBcsTgaI6lbBVm9lcKxvL5Sg53zBsMvfakpU4RTLSyRbD44z0="
after_success:
- |

     declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

     # Decrypt the file containing the private key
     # (Note: this is the same as what is generated by the Travis CLI at step 2.5)

     openssl aes-256-cbc \
       -K $encrypted_52de7ff03cea_key \
       -iv $encrypted_52de7ff03cea_iv \
       -in ".travis/github_deploy_key.enc" \
       -out "$SSH_FILE" -d

     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

     # Enable SSH authentication

     chmod 600 "$SSH_FILE" \
       && printf "%s\n" \
            "Host github.com" \
            "  IdentityFile $SSH_FILE" \
            "  LogLevel ERROR" >> ~/.ssh/config
install:
  - |
    brew install create-dmg
    security create-keychain -p travis build.keychain
    security default-keychain -s build.keychain
    security unlock-keychain -p travis build.keychain
    echo $CERTIFICATE_OSX_P12 | base64 --decode > certificate.p12
    security import certificate.p12 -k build.keychain -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign
    security set-key-partition-list -S apple-tool:,apple: -s -k travis build.keychain

script:
    - xcodebuild clean build -project ReaderTranslator.xcodeproj -scheme 'ReaderTranslatorMac' -sdk macosx -configuration Debug -derivedDataPath ./build | xcpretty -c
    - cp -R build/Build/Products/Debug/ReaderTranslatorMac.app .
    - create-dmg --volname "Application Installer" --hide-extension "Application.app" --app-drop-link 600 185 "ReaderTranslatorMac.dmg" "ReaderTranslatorMac.app/"
    - find ReaderTranslatorMac *.dmg

deploy:
  provider: releases
  api_key:
    secure: "ceWI2swzBzRILNZShuxTkRYis9E4r3q4TDseAOWHC5Matt4XLpbDMk4PV20s3TCjP3hC/eHVjtiXlP8GrY5dN3pjjEHLV1mw28fXb8OVP7sA1c3RjIY3ETgGfP/uGMi4ZcfCFO+RBsEAPPiUFiNQ9C1HqE5vXwuU08HIKPziDuOWOw6gCTXJwEr3fJu73o5Fwk089M45l8+uS1c+wgIhgbjbvHlAwlZjrxpS4PcuHPvh5M0y5TJ1mDDJCPr/Do8Ns/flV8eLGK+vLR9VRKgbCoianoH5vhclXkYnLXlIgBfKUz0j/KYLmLa0FYRIekSTZTye8TG1+XuMisy5IjSRZZPpFL9bXcbUdWzmw30kOWzHQF8Yfn96nqhgq4V+xWNY6ww/UvyC4tnNNGW9C4VdqjAmZIPN9DkKmfJpyR8GdGtBwonDDzxsQxlkyrzvCtCu6HnYmIFieJ7QjJSTyZwlhNWDJh7WBQDq6O80VIBAp1GofBg9uInn0CaNifmGYYMhQGCe5wT8HyaR0Sdnuf5C/Hm1NTmG3rfVNHZAhd9CjD6+4Q2U/+mT+1XKrB1QKXNQinwctOVqK7dUbY3zBMxj8/DiCBPnS7WUj1n5Mu0mBK8c3MdNTzzyGjvi5ciBcsTgaI6lbBVm9lcKxvL5Sg53zBsMvfakpU4RTLSyRbD44z0="
  file_glob: true
  file:
    - ReaderTranslatorMac
    - ReaderTranslatorMac.dmg
  skip_cleanup: true
  on:
    tags: true
    repo: filimo/ReaderTranslator
    branch: master
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+.*$/
