os: osx
osx_image: xcode11.1
language: swift
install:
  - |
    security create-keychain -p travis build.keychain
    security default-keychain -s build.keychain
    security unlock-keychain -p travis build.keychain
    echo $CERTIFICATE_OSX_P12 | base64 --decode > certificate.p12
    security import certificate.p12 -k build.keychain -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign
    security set-key-partition-list -S apple-tool:,apple: -s -k travis build.keychain

script:
    xcodebuild
    clean
    build
    -scheme "ReaderTranslatorMac"
    -configuration Debug

